### ISSUE TITLE
Illegal Character in column name - Source Oracle

### ISSUE THREAD

**Issue by Shad107** [Apicurio/apicurio-registry#3612] opened 2023-08-29 09:45 UTC
I synchronize an Oracle source with Debezium and use apicurio schema registry.

I just discovered that a table is not synchronizing with the error 'org.apache.avro.SchemaParseException: Illegal character in: OriginDisbursementDetailId ' and 'ERROR [task-thread-:LogReporter@66] - Error encountered in task . Executing stage 'VALUE_CONVERTER' with class 'io.apicurio.registry.utils.converter.AvroConverter'.

The problem is that this is due to a space in the column name, unfortunately I'm not the master of the source schema.

In the logs provided you'll see that the column name 'OriginDisbursementDetailId ' contains a space at the end.

Can you check this problem?

## Description

**Registry
Version**: Docker image -> apicurio/apicurio-registry-kafkasql:2.4.4.Final

**Persistence type**: Debezium, initial snapshot

### Environment

Docker version 20.10.25, build 20.10.25-0ubuntu1~22.04.1

### Steps to Reproduce

To reproduce it

1. Create table with column name with space end
2. Add entry with NULL value
3. Synchronize initial snapshot with debezium 2.3

### Expected vs Actual Behaviour

it's best to ignore the white spaces in the column name, or at worst to have a more explicit error.

### Logs
```
org.apache.avro.SchemaParseException: Illegal character in: OriginDisbursementDetailId 
	at org.apache.avro.Schema.validateName(Schema.java:1607)
	at org.apache.avro.Schema.access$400(Schema.java:92)
	at org.apache.avro.Schema$Field.<init>(Schema.java:556)
	at org.apache.avro.Schema$Field.<init>(Schema.java:595)
	at io.apicurio.registry.utils.converter.avro.AvroData.addAvroRecordField(AvroData.java:1063)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:903)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchemaWithCycle(AvroData.java:1025)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:890)
	at io.apicurio.registry.utils.converter.avro.AvroData.addAvroRecordField(AvroData.java:1062)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:903)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:735)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:729)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectData(AvroData.java:368)
	at io.apicurio.registry.utils.converter.AvroConverter.applySchema(AvroConverter.java:81)
	at io.apicurio.registry.utils.converter.SerdeBasedConverter.fromConnectData(SerdeBasedConverter.java:117)
	at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:64)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.lambda$convertTransformedRecord$6(AbstractWorkerSourceTask.java:482)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:180)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:214)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.convertTransformedRecord(AbstractWorkerSourceTask.java:482)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.sendRecords(AbstractWorkerSourceTask.java:392)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:359)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-08-28 11:08:22,673 - ERROR [task-thread-AlissiaTestTable-0:LogReporter@66] - Error encountered in task AlissiaTestTable-0. Executing stage 'VALUE_CONVERTER' with class 'io.apicurio.registry.utils.converter.AvroConverter'.
org.apache.avro.SchemaParseException: Illegal character in: OriginDisbursementDetailId 
	at org.apache.avro.Schema.validateName(Schema.java:1607)
	at org.apache.avro.Schema.access$400(Schema.java:92)
	at org.apache.avro.Schema$Field.<init>(Schema.java:556)
	at org.apache.avro.Schema$Field.<init>(Schema.java:595)
	at io.apicurio.registry.utils.converter.avro.AvroData.addAvroRecordField(AvroData.java:1063)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:903)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchemaWithCycle(AvroData.java:1025)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:890)
	at io.apicurio.registry.utils.converter.avro.AvroData.addAvroRecordField(AvroData.java:1062)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:903)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:735)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectSchema(AvroData.java:729)
	at io.apicurio.registry.utils.converter.avro.AvroData.fromConnectData(AvroData.java:368)
	at io.apicurio.registry.utils.converter.AvroConverter.applySchema(AvroConverter.java:81)
	at io.apicurio.registry.utils.converter.SerdeBasedConverter.fromConnectData(SerdeBasedConverter.java:117)
	at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:64)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.lambda$convertTransformedRecord$6(AbstractWorkerSourceTask.java:482)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:180)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:214)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.convertTransformedRecord(AbstractWorkerSourceTask.java:482)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.sendRecords(AbstractWorkerSourceTask.java:392)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:359)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:75)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by EricWittmann** [comment] 2023-08-30 14:05
Thank you for explaining the issue well.  Clearly if there is a database column name with characters that are not supported by an Avro schema name, there will be a problem.  In this **particular** case (a space at the end of the column name) I think we would probably push back and suggest trying to fix the schema.  I know you've said you aren't the schema owner, but someone is - and it couldn't possibly have been intentional to name the column in that way.

That said, I'm guessing there are other cases that are more valid, where a column name might contain characters that aren't allowed in an Avro schema name.  So to that end I think we should probably just create a simple sanitize method to deal with this.  Honestly it might not be a huge priority, but it shouldn't be difficult to do. 

@Shad107 if you were interested in contributing a fix like I've described above, I'd be happy trying to help point you in the right direction of a solution.  If not that's OK too, but I'm not sure when we might come around to a fix for this.

**Comment by Shad107** [comment] 2023-08-30 14:21
Hello Eric,

Thanks for response, I'll try to correct this problem, but you'll have to tell me where to start.

Looking forward to hearing from you

**Comment by Shad107** [comment] 2023-08-30 15:29
I check rapidly code, but a found in 'AvroData.java' line 1061 and add fieldName.trim()

**Comment by EricWittmann** [comment] 2023-09-05 15:37
I tried a fix for this here:  https://github.com/Apicurio/apicurio-registry/pull/3628

**Comment by EricWittmann** [comment] 2023-09-05 15:38
Something a bit more inclusive than just doing a `trim()` on the name.  I'm sanitizing the name and namespace to **only** those characters allowed by the Avro standard.

**Comment by Naros** [comment] 2023-09-05 18:59
Hi @Shad107, can you do me a favor and share your Debezium connector configuration?

**Comment by Naros** [comment] 2023-09-05 19:50
Hi @Shad107 and @EricWittmann I can confirm that the issue here is likely the fact that the Debezium configuration is not supplemented with the following settings:
```
schema.name.adjustment.mode=avro
field.name.adjustment.mode=avro
```
In older versions of Debezium, we automatically defaulted to `avro` but we found that wasn't often the right play for cases where a deployment did not use a schema registry and users may have wanted the events to be emitted with the non-avro characters as part of the schema and/or field names.

In Debezium 2 based on the discussions in [DBZ-5541](https://issues.redhat.com/browse/DBZ-5541), it was discussed that since Kafka makes no preference on one or the other serialization format and that each have their own sets of pros/cons that we should treat the name adjustment accordingly.

Fwiw, I'm concerned that if apicurio patches this to be more flexible, this could lead to situations where a Debezium configuration works with apicurio but won't work for other providers, which could be even more confusing rather than pushing back and enforcing that the issue is with the source connector configuration in the first place.

**Comment by carlesarnal** [comment] 2023-09-06 10:17
Hello @Naros, thanks for the detailed explanation. I wasn't aware of that configuration in Debezium, thank you very much for all the context. I absolutely agree with you, this should not be addressed in Apicurio Registry but fixed with proper Debezium configuration. @Shad107 you can try what Chris described. I'll close this issue for now since there is a viable solution but, if anyone feels otherwise, please, re-open.

**Closed by carlesarnal** 2023-09-06 10:17 UTC
Labels: Bug, area/storage

**Comment by carlesarnal** [comment] 2023-09-12 09:06
Hello @Shad107,

As Chris pointed out, you must set that configuration in Debezium. If you got to the documentation, you can see that both configurations are explicitly mentioned, the `schema.name.adjustment.mode` is set in the example connector [here](https://debezium.io/documentation/reference/stable/configuration/avro.html#apicurio-registry) and there is an entire [section](https://debezium.io/documentation/reference/stable/configuration/avro.html#avro-naming) for conflicts between the column names and the field values in Avro where `field.name.adjustment.mode` is also explicitly mentioned.

If you set those two properties, you should be all set with your configuration.
