### ISSUE TITLE
with ~1200 artifacts (10 versions each) and strimzi storage I'm getting OutOfMemoryError

### ISSUE THREAD

**Issue by jhutar** [Apicurio/apicurio-registry#888] opened 2020-10-01 11:39 UTC
I think it is caused by calling `/api/artifacts` to list all the artifacts.

In case it is relevant, artifacts are very small:

```
{
  "type": "record",
  "name": "schema_...",
  "namespace": "com.example",
  "fields": [
    {
      "name": "symbol",
      "type": "string"
    },
    {
      "name": "price",
      "type": "string"
    },
    ...and each version have one more {"name": "field_...", "type": "string"} item...
  ]
}
```

Error looks like this:

```
2020-10-01 07:43:35,683 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-2) [Consumer clientId=example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-2-restore-consumer, groupId=null] Subscribed to partition(s): example-apicurioregistry-storage-store-changelog-13, example-apicurioregistry-storage-store-changelog-19, example-apicurioregistry-storage-store-changelog-1
2020-10-01 07:43:35,683 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-1) [Consumer clientId=example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-1-restore-consumer, groupId=null] Subscribed to partition(s): example-apicurioregistry-storage-store-changelog-10
2020-10-01 07:43:35,821 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-2) [Consumer clientId=example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-2-restore-consumer, groupId=null] Subscribed to partition(s): example-apicurioregistry-storage-store-changelog-13, example-apicurioregistry-storage-store-changelog-19, example-apicurioregistry-storage-store-changelog-1
2020-10-01 07:43:35,821 INFO  [io.api.reg.str.uti.LoggingStateRestoreListener] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-1) batch restored: topicPartition=example-apicurioregistry-storage-store-changelog-10, storeName=storage-store, batchEndOffset=3097, numRestored=2
2020-10-01 07:43:35,821 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-1) [Consumer clientId=example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-1-restore-consumer, groupId=null] Subscribed to partition(s): example-apicurioregistry-storage-store-changelog-10
2020-10-01 07:43:36,042 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-1) [Consumer clientId=example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-1-restore-consumer, groupId=null] Subscribed to partition(s): example-apicurioregistry-storage-store-changelog-10
2020-10-01 07:43:36,044 INFO  [io.api.reg.str.uti.LoggingStateRestoreListener] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-2) batch restored: topicPartition=example-apicurioregistry-storage-store-changelog-1, storeName=storage-store, batchEndOffset=3325, numRestored=3
2020-10-01 07:43:36,044 INFO  [io.api.reg.str.uti.LoggingStateRestoreListener] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-2) batch restored: topicPartition=example-apicurioregistry-storage-store-changelog-13, storeName=storage-store, batchEndOffset=3034, numRestored=3
2020-10-01 07:43:36,044 INFO  [io.api.reg.str.uti.LoggingStateRestoreListener] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-2) batch restored: topicPartition=example-apicurioregistry-storage-store-changelog-19, storeName=storage-store, batchEndOffset=3140, numRestored=2
2020-10-01 07:43:36,044 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-2) [Consumer clientId=example-apicurioregistry-96813157-2943-4712-ab87-85704fce7a4e-StreamThread-2-restore-consumer, groupId=null] Subscribed to partition(s): example-apicurioregistry-storage-store-changelog-13, example-apicurioregistry-storage-store-changelog-19, example-apicurioregistry-storage-store-changelog-1
Terminating due to java.lang.OutOfMemoryError: Java heap space
```

**Comment by EricWittmann** [comment] 2020-12-08 17:31
This ended up being caused by a bug in the load testing script that resulted in the artifact size continuing to increase (not being reset per-artifact).  So as the script added more artifacts, each one just got bigger until the java heap ran out (perhaps still earlier than expected).  We need to implement content size limits in registry to catch this sort of problem in the future.  That will be a separate GitHub issue, so I'm going to close this one.

**Closed by EricWittmann** 2020-12-08 17:31 UTC
Labels: Bug
