### ISSUE TITLE
ui - Error searching for artifacts

### ISSUE THREAD

**Issue by rust84** [Apicurio/apicurio-registry#513] opened 2020-05-21 13:44 UTC
I have deployed the apicurio-registry using the registry operator using the streams crd example.

    apiVersion: apicur.io/v1alpha1
    kind: ApicurioRegistry
    metadata:
    name: example-apicurioregistry
    spec:
    image:
        registry: "docker.io/apicurio"
        version: "1.2.0.Final"
    configuration:
        persistence: "streams"
        streams:
        bootstrapServers: "my-cluster-kafka-brokers.kafka.svc.cluster.local:9092"
        # e.g. bootstrapServers: "my-cluster-kafka-bootstrap.kafka.svc:9092"
        applicationId: "example-apicurioregistry"
    deployment:
        replicas: 1
        route: "apicurio-registry.k8s.mydomain.com"

When loading the ui in a browser I receive the following error.

    {
    "message": "Network Error",
    "name": "Error",
    "stack": "Error: Network Error\n    at e.exports (https://apicurio-registry.k8s.mydomain.com/ui/vendors.bundle.a38d8b34fd72ed401365.js:289:56022)\n    at XMLHttpRequest.f.onerror (https://apicurio-registry.k8s.mydomain.com/ui/vendors.bundle.a38d8b34fd72ed401365.js:80:46039)",
    "config": {
        "url": "http://apicurio-registry.k8s.mydomain.com/api/search/artifacts?limit=10&order=asc&over=everything",
        "method": "get",
        "headers": {
            "Accept": "application/json"
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1
    }
    }

However if I port forward to the pod and go to localhost:8080/ui then the artifacts load correctly. 

I am using nginx as the ingress controller in kubernetes. I see 200 responses in the nginx log. I can also curl the artifacts successfully.

    ➜ curl https://apicurio-registry.k8s.mydomaincom/api/artifacts
    ["topic-key","topic-value"]%

**Comment by EricWittmann** [comment] 2020-05-21 14:15
Can you post the contents of the browser's dev console?  There may be some useful information there.

**Comment by EricWittmann** [comment] 2020-06-01 11:37
@rust84 Any way you could copy/paste the contents of the browser dev console to help with debugging this?

**Comment by brokenjacobs** [comment] 2020-08-03 04:30
I just ran into this as well. Looks like the url is not using the X-Forwarded-Proto header being passed in to use the same proto in the uri? Is there any way to force this with a quarkus setting? I haven't found one.

**Comment by brokenjacobs** [comment] 2020-08-03 04:38
VM9:1 Mixed Content: The page at 'https://apicurio.k8s3.***/ui/artifacts' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://apicurio.k8s3.***/api/search/artifacts?limit=10&order=asc&over=everything'. This request has been blocked; the content must be served over HTTPS.

**Comment by brokenjacobs** [comment] 2020-08-03 04:48
The issue appears to be here:
https://github.com/Apicurio/apicurio-registry/blob/b2572d90f76c108fe9ac3716e4e4a4b55b9787e2/app/src/main/java/io/apicurio/registry/ui/servlets/ConfigJsServlet.java#L94

getRequestUrl doesn't include the scheme. From my searching either getRequestURI() is needed or a method checking for the X-Forwarded-Proto header. (or both).

**Comment by brokenjacobs** [comment] 2020-08-03 04:54
One more piece to fixing this. It looks like vert.x provides a handy method on the request, request.isSSL that works if the request has been proxied via the proxy handler. Merged in this patch:
https://github.com/vert-x3/vertx-web/commit/136ff0331679491c3929b317a054082df8595378

So a check of that and then using the appropriate url should fix this issue for the api and ui urls.

**Comment by EricWittmann** [comment] 2020-08-03 16:01
Thanks for adding details about the problem.  That will greatly help implement a fix.

**Comment by forsberg** [comment] 2020-08-11 08:01
Also got hit by this. 

Perhaps an alternative solution is to decrease the amount of information generated into config.js on the server-side to only include the paths for the API etc, and let the javascript on the browser side figure out the rest, e.g. using [document.location](https://developer.mozilla.org/en-US/docs/Web/API/Document/location)

**Comment by EricWittmann** [comment] 2020-08-11 19:46
That's a reasonable suggestion, although the architecture of the UI and API layers doesn't assume they will be deployed under the same domain.  So there may come a day when we separate them out, at which point the browser will not be able to assume the API location.

I think a configuration setting is needed as **part** of the solution to this.  Basically we can have a "best effort" guess that will work most of the time ... but if you run into a problem we'll just have an ENV variable that deployers can set to override the default behavior.

**Comment by forsberg** [comment] 2020-08-18 09:08
I hate to be nagging, but this issue is my main annoyance just now when it comes to getting a full PoC with Apicurio running, as I can't get the registry running behind my nginx ingress with authentication (OIDC) for humans to see. 

I see it's "Accepted in Version 2", but what does that mean timeline-wise? If it's too far away, I might have to try fixing it myself, but neither Java server thingies nor Javascript frontend thingies are quite my cup of tea so that would be unnecessarily time-consuming.

**Comment by EricWittmann** [comment] 2020-08-18 11:53
Actually nagging is very helpful to help set priorities.  :)

If I were to make some changes would you be willing to test them in your environment?  If so, how would you like to receive the changes?  I could push a snapshot docker image to docker hub, for example.

**Comment by forsberg** [comment] 2020-08-18 12:28
Snapshot docker image in docker hub I can easily test for you, no problem.

**Comment by EricWittmann** [comment] 2020-08-18 12:36
Great - which storage variant are you using?

**Comment by forsberg** [comment] 2020-08-18 12:53
kafka-streaming.

**Comment by EricWittmann** [comment] 2020-08-18 12:58
OK great - testing some changes now.  I've added a check for `isSecure()` that will switch the generated URL from `http` to `https` but I honestly don't expect that to work in your environment.  So in addition I've added the following env variables:

* `REGISTRY_UI_CONFIG_UIURL` - explicitly set the UI url that appears in `config.js`
* `REGISTRY_UI_CONFIG_APIURL` - explicitly set the API url that appears in `config.js`

Hopefully one of these approaches will work for you.  If not, I can also add an option to let the browser figure it out (your suggestion).

**Comment by forsberg** [comment] 2020-08-18 13:25
Depends on how isSecure is implemented, if it looks for one of the standard headers (X-Forwarded-Proto, or Forwarded) it will probably work out of the box.

https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

**Comment by EricWittmann** [comment] 2020-08-18 14:48
OK I've pushed to docker hub:  

https://hub.docker.com/layers/apicurio/apicurio-registry-streams/latest-snapshot/images/sha256-1a8a140dfa4340b9f9ea873c1be7972d822af153bd76118005fa78a0809bcb3f?context=explore

Please be aware that I built this from `master` - so be on the lookout for other unexpected issues.  I don't expect any but you never know.  If this works for you then I'll try to get a `1.3.0.Final` community release done asap (this week hopefully).

**Comment by forsberg** [comment] 2020-08-19 09:08
Hmm.. tried both the isSecure() and setting REGISTRY_UI_CONFIG_UIURL/REGISTRY_UI_CONFIG_APIURL, but neither works. 

However, I'm unsure if I'm actually using your build - the link you provided doesn't work for me. The image I'm using is this:

      image: apicurio/apicurio-registry-streams:latest-snapshot

Kubernetes exposes a bit more information about the image:

    containerStatuses:
     - containerID: docker://2462a8da66b9dae802f7a52a6557dc9de2cce97a6981eef21e24eacf5021875d
       image: apicurio/apicurio-registry-streams:latest-snapshot
       imageID: docker-pullable://apicurio/apicurio-registry-streams@sha256:b494c78d77883f6b8fb7c59c2c1cc202a1bce7bc6535d6d47227652bf0810a40

Perhaps the latest-snapshot tag was overwritten during the night and I'm now trying what's on master, not what's in your branch?

**Comment by forsberg** [comment] 2020-08-19 09:32
Built my own docker image from your branch and pushed to my own image registry. 

Setting environment variables seem to provide the desired result. Will experiment a bit with request headers to see if I can trigger the isSecure() check.

**Comment by forsberg** [comment] 2020-08-19 09:36
Nah, can't get isSecure() to work with any request headers I know of which might trigger it. But that was just to expect. 

So I can confirm that the REGISTRY_UI_CONFIG_UIURL and REGISTRY_UI_CONFIG_APIURL environment variables work as intended, and I can access my schema registry from browser via nginx ingress that terminates TLS. 

Thanks!

**Comment by EricWittmann** [comment] 2020-08-19 11:44
OK thanks for the update - you're right about the `latest-snapshot` tag ... that got blasted yesterday when I merged a PR onto `master`.  Sorry about that, I forgot we were doing that in CI.

I'll merge these changes in, but there is still room for improvement here.  I'll add some handling of the `X-Forwarded-Proto` and `X-Forwarded-Host` headers which should provide better out of the box support for this use-case.  I'll wait to close this issue until that is done.

**Closed** 2020-08-19 13:45 UTC
Labels: Bug

**Comment by forsberg** [comment] 2020-08-28 09:59
@EricWittmann - deployed 1.3.0.Final today, and could remove the environment variables - it worked out of the box with an ingress-nginx in front of it, using the X-Forwarded-Proto/X-Forwarded-Host headers that nginx configured as ingress-nginx sends by default.

**Comment by EricWittmann** [comment] 2020-08-28 11:21
Awesome!  Thanks for letting me know that - much appreciated.

**Comment by andrew-musoke** [comment] 2021-02-28 19:07
Not trying to reopen the issue. I have been struggling with getting this to work for a Kubernetes cluster using Istio instead of Nginx. reverse proxy. I fixed it using the following virtual service. 

> Notice the use of `set` and not `add` [header operation](https://istio.io/latest/docs/reference/config/networking/virtual-s

ervice/#Headers-HeaderOperations). For some reason add did not work.

```
apiVersion:  networking.istio.io/v1alpha3
kind:  VirtualService
metadata:
  name: apicurio-registry-virtualservice
  namespace: my-namespace
spec:
  gateways:
  - my-gateway
  hosts:
  - my.domain.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: example-apicurioregistry-service-jcwsh.my-namespace.svc.cluster.local
        port:
          number: 8080
    headers:
      request:
        set:
          X-Forwarded-Proto: https
          X-Forwarded-Host: my.domain.com
```

**Comment by EricWittmann** [comment] 2021-03-01 14:29
@andrew-musoke Do you know if there is some enhancement we could make to the application to automatically detect the correct schema/host/port when using Istio?
