### ISSUE TITLE
Global-id value is 65034875748

### ISSUE THREAD

**Issue by perebaj** [Apicurio/apicurio-registry#2547] opened 2022-06-03 13:44 UTC
I need help to solve this problem, I am creating a **sink connector** with a Kafka topic so that the data is thrown into Big Query, my **producer** already writes the messages in the topic in AVRO format and performs the schema registration in the apicurio registry which is deployed on the same cluster as my kafka (I am using strimzi to manage the Kafka Cluster), but when the messages have to go through the **convert**, the **schema is not found**, and the following error message is always issued

**RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.PathParam("globalId") value is '65034875748'**

I would like the schema to be found automatically using the strategy
**TopicIdStrategy** where the search is done by adding the suffix, value or key to the name of the consumption topic, as it is already being recorded in the apicurio registry

![image](https://user-images.githubusercontent.com/39134841/171865309-5af64b3b-795d-4718-af6a-efa2d30459e1.png)

 
My Kafka Connector configuration yaml file ⬇️⬇️⬇️⬇️

```bash
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: schema-registry-sink-connector
  labels:
    strimzi.io/cluster: kafka-connect-schema-registry-component
spec:
  class: 'com.wepay.kafka.connect.bigquery.BigQuerySinkConnector'
  tasksMax: 1
  config:
    tasks.max: 1
    
    #consumer configs
    topics: 'tb.avro.schema'
    consumer.override.auto.offset.reset: "latest"
    

    #kafka converter configs
    value.converter.schemas.enable: true
    key.converter.schemas.enable: false
    value.converter: "io.apicurio.registry.utils.converter.AvroConverter" 
    value.converter.apicurio.registry.url: "http://my-apicurio-registry-apicurio-registry.kafka.svc.cluster.local:8080"
    key.converter: org.apache.kafka.connect.storage.StringConverter


    #bquery configs
    project: caramel-box
    defaultDataset: 'db_product'
    keyfile: 'svc-account-bquery.json'
    autoCreateTables: false  
    deleteEnabled: false
    upsertEnabled: false
    schemaRetriever: "com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever"
    autoUpdateSchemas: false
    sanitizeTopics: false
    bigQueryPartitionDecorator: false
   
```

The error message I'm getting ⬇️⬇️⬇️⬇️
```bash
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
              at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:206)
              at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:516)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:493)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:332)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
              at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
              at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
              at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
              at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
              at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
              at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
              at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.apicurio.registry.rest.client.exception.RestClientException: RESTEASY003870: Unable to extract parameter from http request: javax.ws.rs.PathParam("globalId") value is '65034875748'
  at io.apicurio.registry.rest.client.impl.ErrorHandler.handleErrorResponse(ErrorHandler.java:64)
  at io.apicurio.rest.client.handler.BodyHandler.lambda$toSupplierOfType$1(BodyHandler.java:46)
  at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:202)
  at io.apicurio.registry.rest.client.impl.RegistryClientImpl.getContentByGlobalId(RegistryClientImpl.java:293)
  at io.apicurio.registry.resolver.AbstractSchemaResolver.lambda$resolveSchemaByGlobalId$1(AbstractSchemaResolver.java:183)
  at io.apicurio.registry.resolver.ERCache.lambda$getValue$0(ERCache.java:132)
  at io.apicurio.registry.resolver.ERCache.retry(ERCache.java:171)
  at io.apicurio.registry.resolver.ERCache.getValue(ERCache.java:131)
  at io.apicurio.registry.resolver.ERCache.getByGlobalId(ERCache.java:111)
  at io.apicurio.registry.resolver.AbstractSchemaResolver.resolveSchemaByGlobalId(AbstractSchemaResolver.java:178)
  at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:148)
  at io.apicurio.registry.serde.AbstractKafkaDeserializer.resolve(AbstractKafkaDeserializer.java:147)
  at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:104)
  at io.apicurio.registry.utils.converter.SerdeBasedConverter.toConnectData(SerdeBasedConverter.java:129)
  at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
  at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:516)
  at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
  at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
```

**Comment by EricWittmann** [comment] 2022-06-03 17:39
We probably need a little more information.  In particular I think we need to know how you're connecting to the registry when producing messages.  Are you using Apicurio provided Kafka SerDes (Java) or are you using Confluent compatible tools?  The error suggests to me that your producer is using confluent tools to register the schema and then produce the messages.  Confluent tools would use 4 bytes to record the ID of the schema in the Kafka message.  Then, because you're using Apicurio SerDes in your consumer (connect), we'll default to 8 bytes when reading the schema ID from the message.

You'll notice from the screenshot you included that the globalId is 15 and the contentId is 13.  So the request that the connector is making (after reading the ID from the Kafka message) should be using one of those values (15 or 13) rather than `65034875748`.  So that's why my guess is your mixing confluent and apicurio tools - because we would be reading 8 bytes for the globalId and getting some random bits and ultimately some random value.

That said, `65034875748` is still a valid ID, so I'm not sure why the request would throw an error vs. just return a 404 Not Found.  Perhaps the quotes were included in the request somehow?  Since the parameter type is a `long` that might cause the failure.  Let me try that now...  nope I cannot reproduce that error.  The only way I can get a similar error is by trying a globalId of something like `FOO`.  Even passing the number in quotes works OK.  I'm at a bit of a loss on this.

**Comment by carlesarnal** [comment] 2022-06-06 15:14
Which version of the confluent libraries are you using? As you can see [here](https://github.com/confluentinc/schema-registry/blob/9ea8eef0c2c86980c0c385abfbae6212d472fbf1/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java#L78) the references field is present in the class and is being returned by the server, so I think you might be using an old version of the confluent library.

**Comment by perebaj** [comment] 2022-06-06 20:29
Ok, I get it and I just updated the  Avro Converter version, but right now I'm having troubles with group 'null' was not found

the configs that I am using are:

```yaml
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://my-apicurio-registry-apicurio-registry.kafka.svc.cluster.local:8080/apis/ccompat/v6"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schema.registry.url: "http://my-apicurio-registry-apicurio-registry.kafka.svc.cluster.local:8080/apis/ccompat/v6"
    apicurio.registry.artifact.group-id: "default"
    value.converter.apicurio.registry.find-latest: true
    apicurio.registry.headers.enabled: false
    value.converter.apicurio.registry.as-confluent: true
```

And the error that pop it up was>>> 

**Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: No artifact with ID 'tb-avro-schema-value' in group 'null' was found.; error code: 40401**

The id exists in the Apicurio
![image](https://user-images.githubusercontent.com/39134841/172239167-5d452d7f-bca1-44d9-a255-11a4337a54fd.png)

ERROR
```YAML
State:  FAILED
      Trace:  org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
              at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:206)
              at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:516)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:493)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:332)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
              at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
              at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
              at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
              at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
              at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
              at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
              at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic tb-avro-schema to Avro:
  at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:124)
  at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
  at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:516)
  at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
  at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
  ... 13 more
Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro value schema version for id 29
  at io.confluent.kafka.serializers.AbstractKafkaSchemaSerDe.toKafkaException(AbstractKafkaSchemaSerDe.java:259)
  at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:186)
  at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:172)
  at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:107)
  ... 17 more
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: No artifact with ID 'tb-avro-schema-value' in group 'null' was found.; error code: 40401
  at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:297)
  at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:367)
  at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:458)
  at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:434)
  at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersionFromRegistry(CachedSchemaRegistryClient.java:297)
  at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersion(CachedSchemaRegistryClient.java:504)
  at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersion(CachedSchemaRegistryClient.java:484)
  at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.schemaVersion(AbstractKafkaAvroDeserializer.java:127)
  at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:168)
  ... 19 more
```

To update the AVRO converter version I just uploaded in a personal repo.
The converter I downloaded in the follow link
https://www.confluent.io/hub/confluentinc/kafka-connect-avro-converter

release link>>>> https://github.com/perebaj/kafka-connect-bigquery/releases/tag/v.7.1.1
And in the connect component in the Kafka-connect YAML config file I downloaded the release, using strimzi build tool
Example, if someone has the same issue.
```yaml

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-schema-registry-component
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  version: 3.1.0
  template: 
    pod:
      imagePullSecrets:
        - name: >secret-component-private-registry<
  bootstrapServers: my-cluster-kafka-external-bootstrap:9094
  build:
      output: # (2)
        type: docker
        image: >private-registry.gitlab.com<
        pushSecret: k>secret-component-private-registry<
        - name: bquery-connector
          artifacts:
          - type: zip
            url: https://github.com/perebaj/kafka-connect-bigquery/releases/download/v1.0.0/wepay-kafka-connect-bigquery-2.3.1.zip
        - name: kafka-connect-avro-converter
          artifacts:
            - type: zip
              url: https://github.com/perebaj/kafka-connect-bigquery/releases/download/v.7.1.1/confluentinc-kafka-connect-avro-converter-7.1.1.zip
  jvmOptions:
    gcLoggingEnabled: false
  config:
    config.providers: file 
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    connector.client.config.override.policy: All

    group.id: schema-registry-connect-cluster
    offset.storage.topic: schema-registry-connect-cluster-offset
    config.storage.topic: schema-registry-connect-cluster-config
    status.storage.topic: schema-registry-connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  externalConfiguration:
    volumes:
      - name: gcp-creds
        secret:
          secretName: svc-account    
```

**Comment by perebaj** [comment] 2022-06-15 23:11
To circumvent that, I am using the schema registry from confluent (# https://github.com/confluentinc/cp-helm-charts/tree/master/charts/cp-schema-registry
) and Kafka-ui (https://github.com/provectus/kafka-ui) to manage and update the schemas

**Comment by EricWittmann** [comment] 2022-08-10 19:24
I'm super late to this party... but how did you add the schema to the registry?  Did you use the UI?  If you do that then you need to be very careful to upload exactly the same content that your app will use, otherwise it won't find it (because it will try to search for it by content hash).  For more information see https://github.com/Apicurio/apicurio-registry/issues/2636

**Comment by carlesarnal** [comment] 2022-10-07 09:50
As Eric pointed out this was caused by #2636 (an incompatibility in the ccompat api) which is now solved, so I'm closing this one as solved.

**Closed by carlesarnal** 2022-10-07 09:50 UTC
Labels: Bug, component/registry, priority/normal
