### ISSUE TITLE
python sdk doesn't handle ifExist in post correctly 

### ISSUE THREAD

**Issue by malteTech** [Apicurio/apicurio-registry#3465] opened 2023-06-28 09:43 UTC
## Description
When using apicurioregistrysdk to to create an artifact I get unexpected behaviour when posting with ifExists parameter set to "RETURN_OR_UPDATE"

**Registry
Version**: apicurio-registry-python-sdk-preview (2.4.14)

**Persistence type**: unknown

### Environment
Ubuntu 22.04, running client in a python 3.11 venv with pycharm.
local apicurio registry running on docker (docker-compose version 1.29.2, build unknown, Docker version 24.0.2, build cb74dfc)

### Steps to Reproduce
Using python sdk, set up a post request to create an artifact with query parameter ifExists set to "RETURN_OR_UPDATE". To specify query parameters use ArtifactsRequestBuilder.ArtifactsRequestBuilderPostQueryParameters class.
The class ArtifactsRequestBuilderPostQueryParameters has the attributes `canonical` and `if_exists` but should have `canonical` and `ifExists`

### Expected vs Actual Behaviour
Using the python sdk to register a schema using ifExists="RETURN_OR_UPDATE" on an already registered schema gets me an 409 response but I want to have as specified in api: 
`RETURN_OR_UPDATE - server returns an existing version that matches the provided content if such a version exists, otherwise a new version is created`

### Logs

```
...
        query_params = ArtifactsRequestBuilder.ArtifactsRequestBuilderPostQueryParameters(
            canonical=True, if_exists='RETURN_OR_UPDATE'
        )

        request_configuration = ArtifactsRequestBuilder.ArtifactsRequestBuilderPostRequestConfiguration(
            headers= {"X-Registry-ArtifactId": artifact_id},
            query_parameters=query_params
        )

        try:
            response = await group.artifacts.post(body=artifact, request_configuration=request_configuration)
            _logger.info(f"response for POST -> {response.__dict__}")
            return response

        except Error as e:
            _logger.error(f"Failed registering: {e.error_code}/{e.message}/{e.detail}")
...
```
Printout from _logger.error is 409/An artifact with ID 'redacted_artifact' in group 'redacted_group' already exists./ArtifactAlreadyExistsException: An artifact with ID 'redacted_artifact' in group 'redacted_group' already exists.

### Other:
First time submitting an issue report to github, please let me know if I've missed information or formatted it incorrectly

**Comment by forsberg** [comment] 2023-06-28 09:48
@andreaTP - we discovered this (@malteTech is a colleague of mine) when trying out the new kiota-based SDK as we discussed in https://github.com/Apicurio/apicurio-registry-client-sdk-python/pull/48, so I think it's of interest to you.

**Comment by andreaTP** [comment] 2023-06-28 09:59
Thanks for the report and happy to hear that you are already using the newly generated SDK!
The bug looks legit from the description, let me have a closer look.

**Comment by andreaTP** [comment] 2023-06-28 11:21
I confirm I can reproduce the error, I'll dig it down and fix it in the Kiota core library asap.
The problem is the encoding of `ifExists` that got dropped in the final query(probably due to a missing mangling back from `if-exists`).

Meanwhile, in the draft PR #3466 you [can see](https://github.com/Apicurio/apicurio-registry/pull/3466/files#diff-d13924b0786de6a51b232362612a1e2ebde4d3599b04355a715d84e5eefbd69aR117-R126) in the test that there is a way to inject the correct parameter for `httpx` basically bypassing the machinery generated by Kiota.
It's ugly but a viable workaround to unblock you until this gets fixed upstream.

Let me know if this helps!

**Comment by andreaTP** [comment] 2023-06-29 12:22
I'll keep this open for tracking purposes, but, the fix for the issue has been merged upstream and next week we should have a release of Kiota.
After that, a full re-generation and upgrade should fix the issue in the generated SDK.

Again, thanks a lot for reporting it, much appreciated!

**Comment by andreaTP** [comment] 2023-07-19 11:25
Fixed by #3466 , please note that the generated code does include a few breaking changes.

Thanks for this report!

**Closed by andreaTP** 2023-07-19 11:25 UTC
Labels: Bug, area/storage

**Comment by forsberg** [comment] 2023-08-07 06:18
I'm being lazy now, but is there a released version of the SDK somewhere with the fix? Pretty please? :)

**Comment by andreaTP** [comment] 2023-08-09 14:16
I missed the message, not that lazy, thanks for the feedback!
