### ISSUE TITLE
Confluent Compatibility Issue with references 

### ISSUE THREAD

**Issue by mouadk** [Apicurio/apicurio-registry#2852] opened 2022-09-29 14:45 UTC
Hello, looks like the Apicurio registry is not compatible with Confluent regarding references.
For example, suppose you have a subject reference named: `com.avro.Category` (already registered), you could reference it in your Avro schema as follows:
```
    {
      "name": "category",
      "doc": "",
      "type": "com.avro.Category"
    }
```
However when trying to register the schema by providing that reference as follows:

```

{
  "references": [
    {
      "name": "com.avro.Category",
      "subject": "com.avro.Category",
      "version": 1
    }
  ],
  "schema":..}

```
 Apicurio returns 

```
{
    "message": "\"com.avro.Category\" is not a defined name. The type of the \"type\" field must be a defined name or a {\"type\": ...} expression.",
    "error_code": 0
}
```

While a Confluent Registry Kafka register it properly. 

Best, 

Mouad

**Comment by carlesarnal** [comment] 2022-09-29 15:10
I'm afraid, but, you'll need to be more specific about the concrete issue by sharing e.g. the curl commands you're executing or something similar. We have tests in place for this and I just tried to register a schema with references using the ccompat api and the schema is successfully created and it can be fetched with all the references.

**Comment by mouadk** [comment] 2022-09-29 15:45
Ok, lets do it step by step: 
1. I have a schema registered under: com.avro.Category 
![Screenshot 2022-09-29 at 17 40 52](https://user-images.githubusercontent.com/32769487/193076636-65784705-1b4d-4228-94b1-c4895503c8d2.png)

2. Now I want to register another schema referencing this one, say: 

` {"references":[{"name":"com.avro.Category","subject":"com.avro.Category","version":1}],"schema":"{\"type\":\"record\",\"name\":\"Schema\",\"namespace\":\"com.avro\",\"fields\":[{\"name\":\"category\",\"type\":\"com.avro.Category\",\"doc\":\"The category type\"}]}"}`

I end up having this error: 
![Screenshot 2022-09-29 at 17 43 32](https://user-images.githubusercontent.com/32769487/193077397-9affff7b-66bd-4b1e-8989-332cd8dfb69f.png)


While using Confluent API, its works. 

![Screenshot 2022-09-29 at 17 44 03](https://user-images.githubusercontent.com/32769487/193077492-ff8ce7db-c617-4c90-b3e4-9132ee9da8bd.png)

**Comment by carlesarnal** [comment] 2022-09-30 08:37
Ah, I have a better sense now, so you're referencing a schema in the same subject. I'll try to reproduce this but yes, this seems like a bug, thanks for reporting it.

**Comment by carlesarnal** [comment] 2022-09-30 09:22
I just did a quick test and everything seems to be working fine. Here are some screenshots:

First schema created:
![imagen](https://user-images.githubusercontent.com/12640103/193238034-aa822d1d-cd75-473b-ad2d-c1622490c466.png)

Schema with the reference created with no issues:
![imagen](https://user-images.githubusercontent.com/12640103/193238134-a5d0857c-a813-4d3a-b983-dfae4956ffc8.png)

And then fetched, and the reference is returned:
![imagen](https://user-images.githubusercontent.com/12640103/193238251-a9f97aa9-bfa4-4ed2-b5d5-ac24deee24af.png)

Given everything seems to be working for me, I have a few more questions:

- Which version of Registry are you using? The support for references was introduced "recently".
- Which rules, if any, do you have enabled?

Thanks!

**Comment by mouadk** [comment] 2022-09-30 09:26
Hello, 

We are using the Apicurio version 2.3.0
I am not sure to understand what you mean by Rules. 

Best, 
Mouad

**Comment by carlesarnal** [comment] 2022-09-30 09:55
By rules I mean compatibility configuration, either global or specific to the subject or schema.

**Comment by mouadk** [comment] 2022-09-30 10:02
I didn't set this value so I suppose it fallback to default one

**Comment by mouadk** [comment] 2022-09-30 10:08
Also what the compatibility has to do with this ?

**Comment by carlesarnal** [comment] 2022-09-30 10:19
I'm just trying to replicate your environment with those questions since I cannot reproduce the issue on my end.

**Comment by mouadk** [comment] 2022-09-30 10:37
Ok thanks

**Comment by mouadk** [comment] 2022-09-30 13:43
I think that there is misconfiguration on our side, I can't say what exactly but looks like it works just fine when I deploy an instance using basic docker compose.

**Comment by mouadk** [comment] 2022-10-03 12:09
Hello, @carlesarnal
I resolved the issue by wipping the backing db. Looks like while I upgraded the registry something in postgres messed with the upgrade, I can't say what exactly. 

Best, 
Mouad

**Comment by carlesarnal** [comment] 2022-10-03 12:27
Thanks for getting back. In that case, I'm closing this one.

**Closed by carlesarnal** 2022-10-03 12:27 UTC
Labels: Bug, component/registry
