### ISSUE TITLE
Error handling should return error codes

### ISSUE THREAD

**Issue by wtrocki** [Apicurio/apicurio-registry#1763] opened 2021-08-17 10:55 UTC
Errors should return human redable message and error code. 
Error codes should be documented. 

Example errors that should have proper codes:
```
- artifact not found "APIREG-01"
- group not found "APIREG-02"
- Cannot recognize artifact type "APIREG-03"
- Provided artifact is not valid
- Provided artifact doesn't meet rules#
- Conflict error when uploading artifact
...
```

Current API Returns java class name and message that cannot be used to determine type of the error.

**Comment by EricWittmann** [comment] 2024-09-05 21:34
Duplicate of: https://github.com/Apicurio/apicurio-registry/issues/1929

**Closed by EricWittmann** 2024-09-05 21:34 UTC
Labels: type/enhancement, component/registry, priority/high
