### ISSUE TITLE
Question about registry versioning

### ISSUE THREAD

**Issue by kcheenu** [Apicurio/apicurio-registry#1398] opened 2021-03-31 06:49 UTC
Do apicurio-registry support custom versioning ? Can the control of versioning be customized ? If so can you please help by giving the pointers ? Thanks.

Regards,
Srini

**Comment by carlesarnal** [comment] 2021-03-31 09:15
Hi @kcheenu. We've introduced this feature in our 2.0 release. Basically, whenever an artifact or artifact version is created, you can specify/override the version by sending the `X-Registry-Version` HTTP request header. The value can be a string. From then on, you can use that version value when executing any operation that requires it.

**Comment by kcheenu** [comment] 2021-03-31 14:46
Thanks carlesarnal. I tried by providing the registry-version in version 2.0 but still it is not picking the version which i'm passing. 
For example below is my http header
content-type: application/json
cookie: e93476e7f1cdab5a19e47be7e3f00e18=c346a568db8736bde01816f5ba9bc2c8; e51ba8f75e96518c01facdf5b9aa13f1=961d71e33fbcd1c87c1a22123dd83820
accept: application/json
accept-encoding: gzip, deflate
accept-language: en-US,en;q=0.8
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
X-Registry-Version: 1s

and I'm calling the Create API - POST /artifacts when I go through the UI I'm still getting the version as 1.

we are using https://hub.docker.com/r/apicurio/apicurio-registry-sql/tags?page=1&ordering=last_updated 
in that 2.0.0.RC1 TAG - apicurio-registry-sql:2.0.0.RC1

Any pointers is highly appreciated.

Regards,
Srini

**Comment by carlesarnal** [comment] 2021-03-31 14:55
Sorry @kcheenu, this feature is not part of 2.0.0.RC1, will be part of the final release.

**Comment by amalkurup89** [comment] 2021-03-31 15:07
@carlesarnal what is ETA for final release version

**Comment by kcheenu** [comment] 2021-04-05 05:48
@carlesarnal Any planned release date for 2.0 final release ? Appreciate your response if you. Thanks.

Regards,
Srini

**Comment by EricWittmann** [comment] 2021-04-06 16:28
The 2.0.0.Final release is scheduled for **very soon**...  Hopefully by the end of this week.

**Comment by EricWittmann** [comment] 2021-04-06 16:29
Sorry for the delay responding to this.  Trying to get a bunch of things done and finalized so we can do the release. :)

**Comment by kcheenu** [comment] 2021-04-07 04:08
Thanks @EricWittmann for the update. Hopefully the custom version feature is also part of this final release and we are eagerly looking to use this feature.

Kind Regards,
Srini

**Comment by EricWittmann** [comment] 2021-04-07 16:03
Yes - I can confirm that the custom version feature will be included in 2.0.0.Final.

**Comment by kcheenu** [comment] 2021-04-14 03:32
@EricWittmann any updates on 2.0.0 final version release date ? Earlier communication says last week but i couldn't see them as of today. Appreciate your response. Thanks.

Kind Regards,
Srini

**Comment by EricWittmann** [comment] 2021-04-14 19:14
The current plan is Friday of this week!

**Comment by carlesarnal** [comment] 2021-05-18 08:16
Closing since this feature has been released in `2.0.0.final`.

**Closed by carlesarnal** 2021-05-18 08:16 UTC
