### ISSUE TITLE
Implement serdes support for Kafka Connect schemas

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#181] opened 2019-12-02 12:29 UTC
Consult with Gunnar Morling on requirements and implementation details.

**Comment by jpechane** [comment] 2020-01-03 14:05
I've tried converter in Kafka Connect instance and failed to start it.
it seems there is a conflict in Jersey pulled by Connect runtime (in lib dir) and RESTeasy that is dependency of apicurio SerDe.
```
connect_1    | Caused by: java.lang.ClassCastException: class org.glassfish.jersey.uri.internal.JerseyUriBuilder cannot be cast to class org.jboss.resteasy.spi.ResteasyUriBuilder (org.glassfish.jersey.uri.internal.JerseyUriBuilder is in unnamed module of loader 'app'; org.jboss.resteasy.spi.ResteasyUriBuilder is in unnamed module of loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @23986957)
connect_1    | 	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.verifyInterface(RestClientBuilderImpl.java:375)
connect_1    | 	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:196)
connect_1    | 	at io.apicurio.registry.client.RegistryClient$ServiceProxy.lambda$invoke$1(RegistryClient.java:163)
connect_1    | 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
connect_1    | 	at io.apicurio.registry.client.RegistryClient$ServiceProxy.invoke(RegistryClient.java:159)
connect_1    | 	at com.sun.proxy.$Proxy39.getArtifactMetaDataByContent(Unknown Source)
connect_1    | 	at io.apicurio.registry.utils.serde.strategy.FindBySchemaIdStrategy.findId(FindBySchemaIdStrategy.java:29)
connect_1    | 	at io.apicurio.registry.utils.converter.ExtJsonConverter.fromConnectData(ExtJsonConverter.java:95)
connect_1    | 	at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:62)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$1(WorkerSourceTask.java:287)
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
connect_1    | 	... 11 more
```
I've removed RESTeasy from converter jars but failed to start again
```
connect_1    | 2020-01-03 13:56:31,243 ERROR  ||  WorkerSourceTask{id=inventory-connector-0} Task threw an uncaught and unrecoverable exception   [org.apache.kafka.connect.runtime.WorkerTask]
connect_1    | org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:287)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:316)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:240)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
connect_1    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect_1    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect_1    | 	at java.base/java.lang.Thread.run(Thread.java:834)
connect_1    | Caused by: java.lang.IllegalStateException: No RestClientBuilderResolver implementation found!
connect_1    | 	at org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver.instance(RestClientBuilderResolver.java:84)
connect_1    | 	at org.eclipse.microprofile.rest.client.RestClientBuilder.newBuilder(RestClientBuilder.java:54)
connect_1    | 	at io.apicurio.registry.client.RegistryClient$ServiceProxy.lambda$invoke$1(RegistryClient.java:159)
connect_1    | 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
connect_1    | 	at io.apicurio.registry.client.RegistryClient$ServiceProxy.invoke(RegistryClient.java:159)
connect_1    | 	at com.sun.proxy.$Proxy39.getArtifactMetaDataByContent(Unknown Source)
connect_1    | 	at io.apicurio.registry.utils.serde.strategy.FindBySchemaIdStrategy.findId(FindBySchemaIdStrategy.java:29)
connect_1    | 	at io.apicurio.registry.utils.converter.ExtJsonConverter.fromConnectData(ExtJsonConverter.java:95)
connect_1    | 	at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:62)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$1(WorkerSourceTask.java:287)
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
connect_1    | 	... 11 more
```
Kafka brings Jersey 2.28 but MP support is only in 2.29

**Comment by alesj** [comment] 2020-01-06 09:53
@jpechane  What if you leave out Jersey?

**Comment by jpechane** [comment] 2020-01-06 10:12
@alesj jersey is hard dependency of Kafka Connect

**Comment by alesj** [comment] 2020-01-06 13:32
@jpechane hmmm, so we need to find a way to tell RestEasy to use its own impl somehow ... ?

**Comment by jpechane** [comment] 2020-01-07 05:10
@alesj Yes, ideally you should find a way how to force using of RESTEasy client when another JAX-RS client is on the classpath.
IMHO (and this is only guess), there is a service loader loading `javax.ws.rs.ext.RuntimeDelegate` service and it probably finds two implementations and use the wrong one.

**Comment by alesj** [comment] 2020-01-08 10:46
@jpechane I have it running -- connect + Registry client ... but it turns out it's a matter of classpath order ... :-)
Investigating more ...

**Comment by alesj** [comment] 2020-01-08 11:56
OK, this is how you make it work:
`
        <dependency>
            <groupId>io.apicurio</groupId>
            <artifactId>apicurio-registry-client</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.jboss.resteasy</groupId>
                    <artifactId>resteasy-client-microprofile</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.ext.microprofile</groupId>
            <artifactId>jersey-mp-rest-client</artifactId>
            <version>2.29.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.ext.microprofile</groupId>
            <artifactId>jersey-mp-config</artifactId>
            <version>2.29.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.geronimo.config</groupId>
            <artifactId>geronimo-config-impl</artifactId>
            <version>1.2.2</version>
        </dependency>
`

**Comment by alesj** [comment] 2020-01-08 11:58
I do need to add a small fix to Registry's client code, to fully make it work.
But I don't see any other way than this -- which you only need to take if you have Jersey on the classpath.

**Comment by jpechane** [comment] 2020-01-08 12:05
So does it mean that with plain Kafka Connect it does not work? As you mentioned you've tried it, what JARs and where did you place into Kafka Connect instance? Thanks

**Comment by alesj** [comment] 2020-01-08 12:17
@jpechane see this pom.xml snippet I posted ... I ran with this inside Connect and it worked as expected.
But you do need #209 first ...

**Comment by EricWittmann** [comment] 2020-03-10 15:03
Marking as closed - I assume this is all working OK now.

**Comment by andritcharthur** [comment] 2020-07-16 21:57
@alesj Sorry to bring up an old issue but I have schema registry up and running with 

`docker run -d -p 8085:8080 -e QUARKUS_PROFILE=prod -e APPLICATION_ID=kafka_schema_registry_id -e KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092  --name schema_registry apicurio/apicurio-registry-kafka`

I also added the contents of https://repo1.maven.org/maven2/io/apicurio/apicurio-registry-distro-connect-converter/1.2.2.Final/apicurio-registry-distro-connect-converter-1.2.2.Final-converter.zip to my kafka plugins folder running with the latest version of Kafka 2.5. I'm still getting the error below. I'm unable to use connect feature at all. Am I missing something? Thank you!

`Caused by: java.lang.IllegalStateException: No RestClientBuilderResolver implementation found!
        at org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver.instance(RestClientBuilderResolver.java:84)
        at org.eclipse.microprofile.rest.client.RestClientBuilder.newBuilder(RestClientBuilder.java:54)
        at io.apicurio.registry.client.GenericClient$ServiceProxy.lambda$invoke$0(GenericClient.java:193)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at io.apicurio.registry.client.GenericClient$ServiceProxy.invoke(GenericClient.java:191)
        at com.sun.proxy.$Proxy34.updateArtifact(Unknown Source)
        at io.apicurio.registry.utils.serde.strategy.AutoRegisterIdStrategy.initialLookup(AutoRegisterIdStrategy.java:32)
        at io.apicurio.registry.utils.serde.strategy.AbstractCrudIdStrategy.findId(AbstractCrudIdStrategy.java:50)
        at io.apicurio.registry.utils.serde.AbstractKafkaSerializer.serialize(AbstractKafkaSerializer.java:66)
        at io.apicurio.registry.utils.converter.SchemalessConverter.fromConnectData(SchemalessConverter.java:105)
        at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$1(WorkerSourceTask.java:292)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
`

**Comment by andritcharthur** [comment] 2020-07-18 17:19
It doesn’t look like any fix was ever committed for this issue. Kafka connect is 100% not useable with this schema registry due to this conflict. I tried pulling down the project but nothing would compile or build to remove resteasy but no luck. Any heLo would be greatly appreciated

**Comment by alesj** [comment] 2020-07-18 20:15
Any test to reproduce this issue?

**Comment by andritcharthur** [comment] 2020-07-20 05:19
Yes, it's the same issue mentioned https://github.com/Apicurio/apicurio-registry/issues/181#issuecomment-570580840. Running the latest Kafka 2.5.0, both Zookeeper and Kafka server
`./bin/zookeeper-server-start.sh ./config/zookeeper.properties`
`./bin/kafka-server-start.sh ./config/server.properties`

load contents of latest [apicurio-registry-distro-connect-converter-1.2.3.Final](https://repo1.maven.org/maven2/io/apicurio/apicurio-registry-distro-connect-converter/1.2.3.Final/apicurio-registry-distro-connect-converter-1.2.3.Final-converter.zip) loaded in the Kafka plugins directory.

Start registry `docker run -d -p 8085:8080 --name schema_registry apicurio/apicurio-registry-mem`

Start Kafka connect with this block in connect-distributed.properties pointing to the local schema registry

`key.converter=io.apicurio.registry.utils.converter.AvroConverter
key.converter.schema.registry.url=localhost:8085/api
value.converter=io.apicurio.registry.utils.converter.AvroConverter
value.converter.schema.registry.url=localhost:8085/api`

Logs will show the errors. Not sure of any work around since I couldn't successfully build the project.

**Comment by alesj** [comment] 2020-07-20 09:29
>> Not sure of any work around since I couldn't successfully build the project.
What failed for you ... ?
(since I just built upstream/master with mvn clean install)

**Comment by andritcharthur** [comment] 2020-07-20 18:53
I get the error below running `mvn clean install`. I ultimately want to be able to run `mvn clean install -DskipTests -Pprod -Pkafka` to build a Kafka specific jar

`...[INFO] Compiling 2 proto file(s) to$HOME\GitHub\apicurio-registry\common\target\generated-sources\protobuf\java
[ERROR] PROTOC FAILED: Access is denied.
[ERROR] C:\Users\andritch\GitHub\apicurio-registry\common\src\main\proto\common.proto [0:0]: Access is denied.
[ERROR] C:\Users\andritch\GitHub\apicurio-registry\common\src\main\proto\serde.proto [0:0]: Access is denied.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for apicurio-registry 1.2.3-SNAPSHOT:
[INFO]
[INFO] apicurio-registry .................................. SUCCESS [  9.037 s]
[INFO] apicurio-registry-common ........................... FAILURE [ 32.570 s]
....`

**Comment by Veramone** [comment] 2020-07-24 13:19
Hi, normally I wouldnt comment on such an old issue but since there's been some activity:

I was running into the same issue using v1.2.2 and not using v.1.1.2. 

It can be reproduced with the following Dockerfile:

```Dockerfile
FROM eu.gcr.io/timewax/rehost/strimzi/kafka:0.17.0-kafka-2.4.0

USER root:root

RUN mkdir -p /opt/kafka/plugins/debezium

COPY ./debezium-connector-mysql/ /opt/kafka/plugins/debezium/

COPY apicurio-registry-distro-connect-converter-1.2.2.Final-converter.tar.gz /opt/kafka/plugins/apicurio-registry-distro-connect-converter/

RUN ( \
    cd /opt/kafka/plugins/apicurio-registry-distro-connect-converter && \
    tar xzf apicurio-registry-distro-connect-converter-1.2.2.Final-converter.tar.gz \
)

USER 1001
```

At a guess, the debezium stuff could safely be removed. I just hope this helps :)

**Comment by EricWittmann** [comment] 2020-07-27 17:32
Any updates on this?  `Access is denied.` seems like a weird result.  @alesj @andritcharthur

**Comment by Veramone** [comment] 2020-07-28 07:58
@andritcharthur 
>  Kafka connect is 100% not useable with this schema registry due to this conflict. 

I actually managed to get around this by dropping the jar files directly in a connector's directory, i.e, like this:

```Dockerfile
FROM strimzi/kafka:0.17.0-kafka-2.4.0

USER root:root

COPY ./artifacts/debezium-* /opt/kafka/plugins/

RUN ( \
    cd /opt/kafka/plugins && \
    tar xzf *.tar.gz && \
    rm *.tar.gz \
)

COPY ./artifacts/apicurio-* /opt/kafka/plugins/debezium-connector-mysql

RUN ( \
    cd /opt/kafka/plugins/debezium-connector-mysql && \
    tar xzf *.tar.gz && \
    rm *.tar.gz \
)

USER 1001
```

**Comment by carlesarnal** [comment] 2023-01-18 08:58
Closing as this was fixed in an old version.

**Closed by carlesarnal** 2023-01-18 08:58 UTC
