### ISSUE TITLE
[/apis/ccompat/v6] Failed to create/retrieve schema `hm.motor-value` (`hm.motor` succeed)

### ISSUE THREAD

**Issue by Hongbo-Miao** [Apicurio/apicurio-registry#3309] opened 2023-05-01 21:50 UTC
# Description

**Registry Version**: `quay.io/apicurio/apicurio-registry/2.3.1.Final`
**Persistence type**: in-memory

## Environment

Kubernetes v1.26.3

### Experiment 1

I can create `hm.motor` by Confluent compatible API by

```shell
curl --location 'http://localhost:8080/apis/ccompat/v6/subjects/hm-iot/versions' \
--header 'Content-Type: application/vnd.schemaregistry.v1+json' \
--data '{
    "schema": "{\"type\": \"record\", \"name\": \"hm.motor\", \"fields\":[{\"name\": \"timestamp\", \"type\": \"long\"}, {\"name\": \"current\", \"type\": \"double\"}, {\"name\": \"voltage\", \"type\": \"double\"}, {\"name\": \"temperature\", \"type\": \"double\"}]}"
}'
```

which returns

```json
{
    "id": 28
}
```

which means succeed.

And I can also get it by Confluent compatible API (ID `28` is from previous step):

```shell
curl --location 'http://localhost:8080/apis/ccompat/v6/schemas/ids/28' \
--header 'Content-type: application/json; artifactType=AVRO'
```

which returns

```json
{
    "schema": "{\"type\": \"record\", \"name\": \"hm.motor\", \"fields\":[{\"name\": \"timestamp\", \"type\": \"long\"}, {\"name\": \"current\", \"type\": \"double\"}, {\"name\": \"voltage\", \"type\": \"double\"}, {\"name\": \"temperature\", \"type\": \"double\"}]}",
    "references": []
}
```

However, I failed to create a schema `hm.motor-value` by Confluent compatible API:

```shell
curl --location 'http://localhost:8080/apis/ccompat/v6/subjects/hm-iot/versions' \
--header 'Content-Type: application/vnd.schemaregistry.v1+json' \
--data '{
    "schema": "{\"type\": \"record\", \"name\": \"hm.motor-value\", \"fields\":[{\"name\": \"timestamp\", \"type\": \"long\"}, {\"name\": \"current\", \"type\": \"double\"}, {\"name\": \"voltage\", \"type\": \"double\"}, {\"name\": \"temperature\", \"type\": \"double\"}]}"
}'
```

which returns an error:

```json
{
    "message": "Failed to discover artifact type from content.",
    "error_code": 42201
}
```

### Experiment 2

I can create `hm.motor` by standard API by

```
curl --location 'http://localhost:35185/apis/registry/v2/groups/hm-group/artifacts' \
--header 'Content-type: application/json; artifactType=AVRO' \
--header 'X-Registry-ArtifactId: hm-iot' \
--data '{
    "type": "record",
    "namespace": "com.hongbomiao",
    "name": "hm.motor",
    "fields": [
        {
            "name": "timestamp",
            "type": "long"
        },
        {
            "name": "current",
            "type": "double"
        },
        {
            "name": "voltage",
            "type": "double"
        },
        {
            "name": "temperature",
            "type": "double"
        }
    ]
}'
```

Later I can retrieve by Confluent compatible API by (ID `30` is from previous step):

```shell
curl --location 'http://localhost:8080/apis/ccompat/v6/schemas/ids/30' \
--header 'Content-type: application/json; artifactType=AVRO'
```

which returns

```
{"schema":"{\n    \"type\": \"record\",\n    \"namespace\": \"com.hongbomiao\",\n    \"name\": \"hm.motor\",\n    \"fields\": [\n        {\n            \"name\": \"timestamp\",\n            \"type\": \"long\"\n        },\n        {\n            \"name\": \"current\",\n            \"type\": \"double\"\n        },\n        {\n            \"name\": \"voltage\",\n            \"type\": \"double\"\n        },\n        {\n            \"name\": \"temperature\",\n            \"type\": \"double\"\n        }\n    ]\n}","references":[]}
```

### Experiment 3

I can create `hm.motor-value` by standard API by

```
curl --location 'http://localhost:8080/apis/registry/v2/groups/hm-group/artifacts' \
--header 'Content-type: application/json; artifactType=AVRO' \
--header 'X-Registry-ArtifactId: hm-iot' \
--data '{
    "type": "record",
    "namespace": "com.hongbomiao",
    "name": "hm.motor-value",
    "fields": [
        {
            "name": "timestamp",
            "type": "long"
        },
        {
            "name": "current",
            "type": "double"
        },
        {
            "name": "voltage",
            "type": "double"
        },
        {
            "name": "temperature",
            "type": "double"
        }
    ]
}'
```

But later I cannot retrieve by Confluent compatible API by (ID `31` is from previous step):

```shell
curl --location 'http://localhost:8080/apis/ccompat/v6/schemas/ids/31' \
--header 'Content-type: application/json; artifactType=AVRO'
```

which returns

```
{"message":"Failed to discover artifact type from content.","error_code":0}
```

## Expected vs Actual Behavior

I expect I can use compatible REST API to create a AVRO schema with name `hm.motor-value`  and also retrieve it by later.

## Logs

This is the log in Experiment 1 when create schema with name `hm.motor-value`:

```shell
2023-05-01 21:51:48 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-3230) apicurio.audit action="register" result="failure" src_ip="127.0.0.1" error_msg="Failed to discover artifact type from content." artifact_id="hm-group"
```

**Comment by Hongbo-Miao** [comment] 2023-05-02 02:01
I kind of getting it, AVRO does not allow `-` based on https://github.com/mtth/avsc/issues/323#issuecomment-708846217

which is why Confluent compatible API failed.

However, for standard API

```shell
curl --location 'http://localhost:35185/apis/registry/v2/groups/hm-group/artifacts' \
--header 'Content-type: application/json; artifactType=AVRO' \
--header 'X-Registry-ArtifactId: hm-iot' \
--data '{
    "type": "record",
    "namespace": "com.hongbomiao",
    "name": "hm.motor",
    "fields": [
        {
            "name": "timestamp",
            "type": "long"
        },
        {
            "name": "current",
            "type": "double"
        },
        {
            "name": "voltage",
            "type": "double"
        },
        {
            "name": "temperature",
            "type": "double"
        }
    ]
}'
```

Right now it does not do verification and just create successfully.

I think worth a verification when use header `'Content-type: application/json; artifactType=AVRO'`.

**Comment by carlesarnal** [comment] 2023-05-02 09:44
You find the problem on your own, which is great. Avro does not allow dashes in the name of the schema. About the Registry API, verifications are disabled by design, but you can enable the global validity rule to ensure that the same checks are also performed there. 

Since you found the problem with the schema and the other thing is intended by design (and there is a feature to enable the same behaviour) I'm closing this.

Thanks!

**Closed by carlesarnal** 2023-05-02 09:44 UTC
Labels: Bug, area/compatibility, area/rest-api, area/storage

**Comment by Hongbo-Miao** [comment] 2023-05-02 17:19
Thanks @carlesarnal Could you link a document regarding global validity rule? Thanks!

**Comment by Hongbo-Miao** [comment] 2023-05-03 18:34
For future people, here it is:

<img width="937" alt="image" src="https://user-images.githubusercontent.com/3375461/236009503-8ff3d6af-453c-47db-a9a8-0b061f9fa515.png">

Now this

```shell
curl --location 'http://localhost:35185/apis/registry/v2/groups/hm-group/artifacts' \
--header 'Content-type: application/json; artifactType=AVRO' \
--header 'X-Registry-ArtifactId: hm.motor-value' \
--data '{
    "type": "record",
    "namespace": "com.hongbomiao",
    "name": "hm.motor-value",
    "fields": [
        {
            "name": "timestamp",
            "type": "long"
        },
        {
            "name": "current",
            "type": "double"
        },
        {
            "name": "voltage",
            "type": "double"
        },
        {
            "name": "temperature",
            "type": "double"
        }
    ]
}'
```

will return

```json
{
    "causes": [],
    "message": "Syntax violation for Avro artifact.",
    "error_code": 409,
    "detail": "SchemaParseException: Illegal character in: motor-value",
    "name": "RuleViolationException"
}
```

However, I found an inconsistent behavior between UI and REST API, I posted at https://github.com/Apicurio/apicurio-registry/issues/3314
