### ISSUE TITLE
Hibernate exception when deploying JPA prod

### ISSUE THREAD

**Issue by yeralin** [Apicurio/apicurio-registry#284] opened 2020-02-20 15:40 UTC
While deploying `apicurio/apicurio-registry-jpa:latest` image with:
```
- name: QUARKUS_PROFILE
  value: prod
- name: QUARKUS_DATASOURCE_URL
  value: {{ .Values.postgresql.postgresqlUrl }}
- name: QUARKUS_DATASOURCE_USERNAME
  value: {{ .Values.postgresql.postgresqlUsername }}
- name: QUARKUS_DATASOURCE_PASSWORD
  value: {{ .Values.postgresql.postgresqlPassword}}
```
Receive:
```
Hibernate:

    drop table meta if exists
2020-02-20 15:32:55,836 WARN  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (main) GenerationTarget encountered exception accepting command : Error executing DDL "
    drop table meta if exists" via JDBC Statement: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "
    drop table meta if exists" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlString(SchemaDropperImpl.java:375)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlStrings(SchemaDropperImpl.java:359)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropFromMetadata(SchemaDropperImpl.java:241)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.performDrop(SchemaDropperImpl.java:154)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:126)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:112)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:145)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:320)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:65)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:109)
	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:57)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:82)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits78.deploy_0(HibernateOrmProcessor$startPersistenceUnits78.zig:51)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits78.deploy(HibernateOrmProcessor$startPersistenceUnits78.zig:70)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:234)
	at io.quarkus.runtime.Application.start(Application.java:87)
	at io.quarkus.runtime.Application.run(Application.java:210)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "if"
  Position: 22
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:267)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:232)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 23 more
```
Same thing for other tables.

Similarly:
```
2020-02-20 15:32:55,914 WARN  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (main) GenerationTarget encountered exception accepting command : Error executing DDL "
    create table artifacts (
       global_id bigint not null,
        artifact_id varchar(255) not null,
        value blob not null,
        version bigint not null,
        primary key (global_id)
    )" via JDBC Statement: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "
    create table artifacts (
       global_id bigint not null,
        artifact_id varchar(255) not null,
        value blob not null,
        version bigint not null,
        primary key (global_id)
    )" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applySqlString(SchemaCreatorImpl.java:439)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applySqlStrings(SchemaCreatorImpl.java:423)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:314)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:166)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:135)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:121)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:156)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:320)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:65)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:109)
	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:57)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:82)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits78.deploy_0(HibernateOrmProcessor$startPersistenceUnits78.zig:51)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits78.deploy(HibernateOrmProcessor$startPersistenceUnits78.zig:70)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:234)
	at io.quarkus.runtime.Application.start(Application.java:87)
	at io.quarkus.runtime.Application.run(Application.java:210)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: org.postgresql.util.PSQLException: ERROR: type "blob" does not exist
  Position: 122
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:267)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:232)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 23 more
```
In PostgreSQL there is no `blob` type but `bytea`.

Seems like the driver doesn't execute PostgreSQL compatible statements.

**Comment by yeralin** [comment] 2020-02-20 15:42
PostgreSQL 11.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

**Comment by yeralin** [comment] 2020-02-20 15:55
I think the order of the statements should be: `drop table if exists meta`

**Comment by yeralin** [comment] 2020-02-20 16:39
After building my own docker image `mvn clean install -DskipTests -Pprod -Pjpa -Ddocker` and running it, I no longer see issues.

I suspect that `apicurio/apicurio-registry-jpa:latest` was built under `dev` profile? I might be wrong about my conclusion.

**Comment by EricWittmann** [comment] 2020-02-20 16:55
Would I be correct in interpreting this as "-jpa fails unless built with -Pprod"?

@jsenko can you comment on this?  Perhaps test to see if the JPA version works with postgresql when built without `-Pprod`.  

I'm pretty sure that the -latest build was done as a dev build, because the most recent build was a snapshot/non-release build.  And the -latest tag is pushed for both snapshot and non-release builds. The next time a release is done, there will be a new `latest-release` tag.  But regardless, the JPA variant should work even when building as dev, I would hope.

**Comment by jsenko** [comment] 2020-02-25 17:01
I think the issue is caused by the images being built in `dev`, because it determines which JDBC driver is used:
https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/resources/application.properties#L12
I'll try to reproduce, but it will probably work if you provide `QUARKUS_PROFILE=prod` environment variable to the images.

I've added some explanation to #283 and we can decide if this is correct behavior

**Comment by carlesarnal** [comment] 2020-05-14 13:18
As @jsenko mentioned, this problem is caused by the image being built with the `dev` profile. As you can read here [Property "quarkus.datasource.driver" not overwritten](https://github.com/quarkusio/quarkus/issues/5129) the quarkus data source property is a build time property. So `-prod` option will cause the application to determine that the driver is the PostgreSQL one. Same applies for the dev profile, in that case, the H2 driver will be resolved.

**Comment by EricWittmann** [comment] 2020-05-14 13:45
OK I remember this issue now.  I should have reviewed it before re-assigning, sorry @carlesarnal - so we just need to make sure we build with -Pprod whenever we create the docker images.  I think this is being done now.  I'll verify and then close this issue.

**Comment by EricWittmann** [comment] 2020-05-14 13:46
OK I've confirmed - all docker builds are done with -Pprod enabled.  Closing this.

**Closed by EricWittmann** 2020-05-14 13:46 UTC
