### ISSUE TITLE
Cache or page possibly costly operations

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry#364] opened 2020-04-08 15:46 UTC
`getArtifactIds` operation will become costly unless cached or paged

See also #359

**Comment by EricWittmann** [comment] 2020-04-09 11:48
Yes I think this is not a useful operation but exists because the confluent schema registry has it.  Once the UI and corresponding back-end search API are complete, usage of this operation should be discourage.  What we should do is LIMIT the number of artifact IDs that this returns to some sensible number (100? 500? 1000?) to avoid the possibility of destroying the server.  Then we can update the documentation of this operation to explain the LIMIT and discourage its use... and point the user to the search API.

**Comment by EricWittmann** [comment] 2020-04-30 13:40
Possible duplicate of https://github.com/Apicurio/apicurio-registry/issues/328

**Comment by EricWittmann** [comment] 2020-05-21 19:15
Closing as duplicate.

**Closed by EricWittmann** 2020-05-21 19:15 UTC
Labels: Duplicate, Enhancement, Quality
