### ISSUE TITLE
Format and indent JSON schemas

### ISSUE THREAD

**Issue by gunnarmorling** [Apicurio/apicurio-registry#684] opened 2020-07-03 14:12 UTC
When looking at a JSON schema in the UI, it's one large long line, which isn't very practical to read. This should be formatted and indented correctly.

**Comment by EricWittmann** [comment] 2020-07-27 12:17
Closing this issue as a duplicate of https://github.com/Apicurio/apicurio-registry/issues/649

**Closed by EricWittmann** 2020-07-27 12:17 UTC
Labels: Duplicate
