### ISSUE TITLE
REST API POST /search/versions and POST /search/artifacts not finding artifacts in group

### ISSUE THREAD

**Issue by wolfchimneyrock** [Apicurio/apicurio-registry#4934] opened 2024-07-25 16:26 UTC
## Description

**Registry
Version**: 3.0.0.M3
**Persistence type**: sql / postgres

Environment: RHEL8

After creating artifacts with firstVersion (tried json, avro, and protobuf) in a group, which can be subsequently be retrieved from the registry with the GET /groups/.../artifacts/.../versions/.../content endpoint, using POST /search/versions and POST /search/artifacts with the schema content payload returns 0 artifacts / versions.

using linux tool `sha256sum` I can verify that the content table in the database has the correct contentHash, and in fact if I do request

GET /ids/contentHashes/bea800d700663345de792fc21ec17aa21b799724f6f2c00b1e01979c4f73c8c2

then the correct results are returned (but there is no way to see the version metadata from that query)

also if I create an artifact without a group (i.e. using POST /groups/default/artifacts) then POST /search/artifacts and POST /search/versions returns the expected correct results.

**Comment by wolfchimneyrock** [comment] 2024-07-25 16:32
strangely, both of these queries return results for artifacts in a group:

`POST /search/artifacts?artifactId=myartifact` and
`POST /search/versions?version=0.0.1`

but the point of /search/* is to determine what the artifactIds / versions available are given some content, so it is broken if we have to provide them in the query

**Comment by carlesarnal** [comment] 2024-11-12 08:51
Hello @wolfchimneyrock,

Are you facing this with the latest release? I'm not able to reproduce this behaviour for it (I know this issue is a bit old) and we have unit tests for this operation, so I'm closing the issue as fixed. If you face it again, please, re-open and I'll take another look.

**Closed by carlesarnal** 2024-11-12 08:51 UTC
Labels: type/bug, component/registry, priority/high, area/rest-api, area/storage
