### ISSUE TITLE
Invalid Return Type When Subject Version Not Found

### ISSUE THREAD

**Issue by nbonavia** [Apicurio/apicurio-registry#2226] opened 2022-02-01 07:57 UTC
I came across a scenario where I have created a very simple schema on both apicurio registry and confluent schema registry. I hit the below rest api with both the apicurio and confluent schema, and the subject has been created successfully: -

```
curl --request POST 'http://apcrg.localhost/apis/ccompat/v6/subjects/foobar/versions' \
--header 'Content-Type: application/json' \
--header 'Accept: application/vnd.schemaregistry.v1+json, application/vnd.schemaregistry+json, application/json' \
--data-raw '{
     "schema": "{\"type\": \"string\"}"
}'
```

Unfortunately when validating an existing schema, (note I changed the type, so the schema does not match) using the below command: -

```
curl --request POST 'http://apcrg.localhost/apis/ccompat/v6/subjects/foobar' \
--header 'Content-Type: application/json' \
--header 'Accept: application/vnd.schemaregistry.v1+json, application/vnd.schemaregistry+json, application/json' \
--data-raw '{
     "schema": "{\"type\": \"int\"}"
}'
```

It seems that Apicurio Registry is returning error code <40401> rather than <40403>, as returned by Confluent schema registry. 

This inconsistency is causing issues in ksqldb not creating a schema version if an exact schema generated by ksqldb does not match any of the subject's versions.

**Comment by eshepelyuk** [comment] 2022-02-01 17:23
Adding some notes, 

The bug is caused by [this API](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)) that is called by `ksqldb` when it start to consume a topic ( on select from a stream).
apucurio registry returns 404 and this causes a chain of failures. Since there's no way to see the request body in logs of Apicurio registry - it's hard to say what exactly causes this error.

**Comment by EricWittmann** [comment] 2022-02-03 19:47
OK thank you for the report.  Logged as a bug and assigned.

**Comment by eshepelyuk** [comment] 2022-02-03 19:55
@EricWittmann please close this bug since initial description is invalid.
we've been able to debug / investigate the issue and we're going to publish a better bug report with reproducible stepas.

**Closed** 2022-02-04 07:59 UTC
Labels: Bug

**Comment by EricWittmann** [comment] 2022-02-04 16:37
Great thanks @eshepelyuk !
