### ISSUE TITLE
2.0.0.RC1 - /apis/registry/v2/search/artifacts HTTP 500 error

### ISSUE THREAD

**Issue by tszappanos** [Apicurio/apicurio-registry#1315] opened 2021-03-09 18:56 UTC
```
java.io.UncheckedIOException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
    at io.apicurio.registry.utils.kafka.ProtoSerde.deserialize(ProtoSerde.java:44)
    at io.apicurio.registry.utils.kafka.ProtoSerde.deserialize(ProtoSerde.java:26)
    at org.apache.kafka.streams.state.StateSerdes.valueFrom(StateSerdes.java:160)
    at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.outerValue(MeteredKeyValueStore.java:207)
    at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.access$100(MeteredKeyValueStore.java:47)
    at org.apache.kafka.streams.state.internals.MeteredKeyValueStore$MeteredKeyValueIterator.next(MeteredKeyValueStore.java:245)
    at org.apache.kafka.streams.state.internals.MeteredKeyValueStore$MeteredKeyValueIterator.next(MeteredKeyValueStore.java:222)
    at org.apache.kafka.streams.state.internals.CompositeKeyValueIterator.next(CompositeKeyValueIterator.java:67)
    at org.apache.kafka.streams.state.internals.CompositeKeyValueIterator.next(CompositeKeyValueIterator.java:25)
    at org.apache.kafka.streams.state.internals.DelegatingPeekingKeyValueIterator.hasNext(DelegatingPeekingKeyValueIterator.java:67)
    at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
    at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
    at io.apicurio.registry.utils.streams.distore.KeyValueStoreGrpcImplLocalDispatcher.drainToKeyValue(KeyValueStoreGrpcImplLocalDispatcher.java:185)
    at io.apicurio.registry.utils.streams.distore.KeyValueStoreGrpcImplLocalDispatcher.filter(KeyValueStoreGrpcImplLocalDispatcher.java:84)
    at io.apicurio.registry.utils.streams.distore.proto.KeyValueStoreGrpc$MethodHandlers.invoke(KeyValueStoreGrpc.java:575)
    at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
    at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
    at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84)
    at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawLittleEndian64(CodedInputStream.java:1157)
    at com.google.protobuf.CodedInputStream$ArrayDecoder.readFixed64(CodedInputStream.java:773)
    at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:541)
    at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:521)
    at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:634)
    at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:308)
    at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:834)
    at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:548)
    at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:320)
    at io.apicurio.registry.storage.proto.Str$ArtifactKey.<init>(Str.java:687)
    at io.apicurio.registry.storage.proto.Str$ArtifactKey$1.parsePartialFrom(Str.java:1297)
    at io.apicurio.registry.storage.proto.Str$ArtifactKey$1.parsePartialFrom(Str.java:1291)
    at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
    at io.apicurio.registry.storage.proto.Str$Data.<init>(Str.java:9822)
    at io.apicurio.registry.storage.proto.Str$Data$1.parsePartialFrom(Str.java:12151)
    at io.apicurio.registry.storage.proto.Str$Data$1.parsePartialFrom(Str.java:12145)
    at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
    at 
```

The same exception was thrown in UI on the first screen (artifact list)

Running on the K8S cluster in 2 replicas.
Last 2.0.0.SNAPSHOT was ok.

**Comment by carlesarnal** [comment] 2021-03-09 19:37
Hi @tszappanos. Is this happening with a concrete artifact? If that’s the case, could you please share it so I can try to reproduce it? Thanks!

**Comment by tszappanos** [comment] 2021-03-10 18:47
> 
> 
> Hi @tszappanos. Is this happening with a concrete artifact? If that’s the case, could you please share it so I can try to reproduce it? Thanks!

tested scenario: an avro or wsdl artifact that was uploaded to the kafka stream repository with version 1.3.x or 2.0.0.latest via the UI. see e.g. avro in the attachment 
[Uploading Employee.json…]()

**Comment by carlesarnal** [comment] 2021-03-11 09:48
> @carlesarnal this looks like an error in the streams storage, right?

Yes, it seems an error in the streams storage.

@tszappanos I'm not sure if I understood you properly. If you upload that artifact to any isolated version everything is fine, whatever the version is, 1.3.2.Final, or 2.0.0.RC1, etc. If you're having this problem when trying to use an artifact created in version 1.3.2.Final in a 2.0.0.RC1 application then that error makes sense since they're not directly compatible. We're working on an upgrade process but it's not possible in the first days of 2.0.0.RC1.

Thanks for your interest!

**Comment by tszappanos** [comment] 2021-03-11 12:15
> 
> 
> > @carlesarnal this looks like an error in the streams storage, right?
> 
> Yes, it seems an error in the streams storage.
> 
> @tszappanos I'm not sure if I understood you properly. If you upload that artifact to any isolated version everything is fine, whatever the version is, 1.3.2.Final, or 2.0.0.RC1, etc. If you're having this problem when trying to use an artifact created in version 1.3.2.Final in a 2.0.0.RC1 application then that error makes sense since they're not directly compatible. We're working on an upgrade process but it's not possible in the first days of 2.0.0.RC1.
> 
> Thanks for your interest!

yes this is an upgrade process from 1.3.2 or 2.0.0.latest snapshot to 2.0.0.RC with existing schemas in the repository. when do you plan to complete this process? Thank you for the information

**Comment by EricWittmann** [comment] 2021-03-11 18:42
Ah!  This is an upgrade problem.  That's good to know.   We still need to determine the best way to upgrade the messages in the kafka topics that we use for storage so that they are compatible with 2.0.0.Final.  This was a breaking change due to a host of new features of 2.0.x.

We haven't determined the process yet - but we will be working on it in the timeframe of the next 2 to 3 weeks.

**Comment by carlesarnal** [comment] 2021-03-12 14:41
Closing in favour of #1339.

**Closed by carlesarnal** 2021-03-12 14:41 UTC
Labels: 2.0.x, Bug
