### ISSUE TITLE
Add indentation/newlines to Info Tab for Schema

### ISSUE THREAD

**Issue by forsberg** [Apicurio/apicurio-registry#765] opened 2020-08-18 09:03 UTC
The python library I'm using to upload schema to the reigstry, using the confluent compatibility API, [uploads the JSON](https://github.com/marcosschroh/python-schema-registry-client/blob/master/schema_registry/client/client.py#L243) of the schema in its most compact form.

This leads to it being shown in the Info tab as one very long line, quite unreadable to a user.

I don't know what the specification says on this one, but it would make the UI more usable if the Apicurio frontend would add some newlines and indentation. Probably a a oneline change for someone that knows how to do it.

**Comment by EricWittmann** [comment] 2020-08-18 17:54
Closing as a duplicate of https://github.com/Apicurio/apicurio-registry/issues/649

**Closed by EricWittmann** 2020-08-18 17:54 UTC
