### ISSUE TITLE
Apicurio throwing io.apicurio.registry.storage.ArtifactNotFoundException while uploading a new artifact

### ISSUE THREAD

**Issue by nehasewda** [Apicurio/apicurio-registry#1926] opened 2021-10-11 07:51 UTC
While trying upload a new artifact via Apicurio registry UI, getting io.apicurio.registry.storage.ArtifactNotFoundException.
Kindly help.

**Comment by EricWittmann** [comment] 2021-10-20 12:10
@nehasewda ping

**Comment by nehasewda** [comment] 2021-10-20 17:34
Sorry for the delay.
1. Apicurio image used  - apicurio/apicurio-registry-kafkasql:latest-snapshot
2. Trying to upload an artifact with an ID "out-stream" with a valid json schema.
3. Got the following error "io.apicurio.registry.storage.ArtifactNotFoundException artifact with ID out-stream not found".

Strangely, I was able to upload the same mentioned artifact after few retries.

**Comment by EricWittmann** [comment] 2021-11-01 16:01
OK thanks @nehasewda - intermittent is the worst kind!  We'll keep trying to analyze it, but if you experience it again and can get the server logs and any stack traces that appear in the browser, that would be super helpful.  In addition, if it's possible to get a dump of the kafka topic, that would be even better.  Something like this:

`kafkacat -b localhost:9092 -t kafkasql-journal -Z -O -D \\n--message-delimiter--\\n -e -K \\n----\\n -J > kafkacat-output-2.log`

If you have proprietary schemas in there I understand.  But if not, that full export of all the messages in the topic would be amazing.

**Comment by nehasewda** [comment] 2021-11-02 05:38
Sure @EricWittmann . I will keep a track and pass the information as soon as I encounter this again.
Thanks for the help.

**Comment by EricWittmann** [comment] 2021-11-08 14:40
@nehasewda I think we may figured out the root cause of this issue:

https://github.com/Apicurio/apicurio-registry/issues/1993

**Comment by nehasewda** [comment] 2021-11-08 16:59
@EricWittmann sure. Thanks!

**Comment by EricWittmann** [comment] 2021-12-06 14:22
We are confident that this has been fixed in https://github.com/Apicurio/apicurio-registry/pull/2030

**Closed by EricWittmann** 2021-12-06 14:22 UTC
Labels: Bug
